Repository googleapis/python-data-fusion, pull requests merged in 2021-08, with the labels that each got.

#14 feat: bump release level to production/stable
  .repo-metadata.json
  README.rst
  docs/README.rst
  setup.py
Labels: cla: yes, api: datafusion, api: datafusion

#18 chore: generate python samples templates in owlbot.py
  owlbot.py
Labels: automerge, cla: yes, samples, api: datafusion, api: datafusion

#20 docs: migrate to main branch
  .kokoro/build.sh
  .kokoro/test-samples-impl.sh
  CONTRIBUTING.rst
  README.rst
  docs/conf.py
  owlbot.py
Labels: automerge, cla: yes, api: datafusion, api: datafusion
